version: 2
jobs:
  build:
    docker:
    - image: node:12.3

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "package.json" }}
        - v2-dependencies-
    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v2-dependencies-{{ checksum "package.json" }}
    - run: npm test
    - run: npm publish --access=public
